'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''lblTokenKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTokenKey As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtTokenKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTokenKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTokenSecret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTokenSecret As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtTokenSecret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTokenSecret As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConsumerKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsumerKey As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtConsumerKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConsumerSecret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsumerSecret As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtConsumerSecret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsumerSecret As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDisplaymode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplaymode As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpDisplaymode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDisplaymode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSearchFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchFor As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtSearchFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchFor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCount As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpCount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInterval As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpInterval As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpTemplate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRenderingMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRenderingMode As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''drpRenderingMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpRenderingMode As Global.System.Web.UI.WebControls.DropDownList
End Class
